services:
  # MySQL数据库
  mysql:
    image: mysql:8.0
    container_name: picture-manager-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: liuhan73
      MYSQL_DATABASE: picturemanager
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - picture-manager-network

  # 后端服务
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: picture-manager-backend
    restart: always
    ports:
      - "8080:8080"
    volumes:
      # 持久化存储图片文件
      - ./data/uploads:/root/uploads
      - ./data/thumbnail:/root/thumbnail
    env_file:
      - ./backend/.env
    depends_on:
      - mysql
    networks:
      - picture-manager-network

  # 前端服务
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: picture-manager-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - picture-manager-network

volumes:
  mysql_data:

networks:
  picture-manager-network:
    driver: bridge

